### ISSUE TITLE
please add to requirements for geospatial extension of schema.org

### ISSUE THREAD

**Issue by ghost** [geo4web-testbed/geo-extension-to-schemaorg#2]
Hi @pvgenuchten , @cportele , @azahnen @matthew-spotzi , @dvh , @joostfarla   /cc @lvdbrink please add your ideas to [this file](https://github.com/geo4web-testbed/geo-extension-to-schemaorg/blob/master/requirements.txt) It is a placeholder for the requirements for spatial extension of schema.org.
What are you missing/ what do you find illogical in the current spatial descriptions in schema.org?

**Comment by cportele** [comment]
@liekeverhelst: 

I would use just "location" instead of "hasLocation", but that is more of a personal preference I think. I do not think that the "has" adds anything and where "has" is used it - at least partly - seems to be done to avoid conflict with deprecated properties, e.g. "hasMap" vs "map".

Regarding the list of point/line/polygon: I think there is value in also supporting bbox as a simpler, but commonly used version of a polygon. For example, for the Datasets we typically have just a bbox and the spatial metadata also supports bbox (or envelopes) in this case.

Once question is whether there is a need to support also aggregates (e.g. multi polygons). In the real world this is what exists, e.g. it is quite normal that an adminstrative unit consists of several polygons. This, of course, complicates the encoding so it is something that needs to be balanced.

Regarding crs I think that WGS84 should at least be the default CRS. The question whether other CRSs should be supported depends on the scope of schema.org. Is it mainly for search engines and similar type of uses? Then just WGS84 should be sufficient. If all kinds of data consuming applications are in scope then other CRS would need to be allowed, too. Maybe with a recommendation to also include the WGS84 location as well.

In general I am also concerned about creating yet another representation for geometries. There are so many already in the linked data world alone, see the NOTE in http://w3c.github.io/sdw/bp/#bp-expressing-spatial. I would recommend to just use an existing one that meets the criteria, depending on the scope (see above). If full support is needed then maybe GeoSPARQL could be used.

If for some reason it is not a good idea to reuse something existing, depending on the scope the split into
- shape
- crs
- coordinates
  would not work. Separating shape and coordinates will be difficult, for example, if you include multi geometries or allow holes in polygons as you need more than a sequence of coordinates, but some structure into which multiple sequences of coordinates can be embedded.

(NB: The link in the issue description is a 404, the .txt is missing)

**Comment by ghost** [comment]
all comments processed. close
